"""Hand-built reference plans for the four sample hypotheses in the Fulcrum brief.

These are the depth bar an LLM-generated plan should clear. They are used as:
  1. assertion targets in tests/test_plan_quality.py — every plan here must pass quality.check_plan
  2. data points for future few-shot prompting (not wired in yet)

Prices and supplier identifiers reflect publicly known 2024 catalog data; they are
intentionally conservative (lower bound of typical research-grade pricing).
"""
from __future__ import annotations

from schemas import (
    ExperimentPlan,
    Material,
    ParsedHypothesis,
    ProtocolStep,
    TimelinePhase,
    ValidationMetric,
)


def _step(n: int, title: str, dur: int, desc: str, notes: str, refs: list[str]) -> ProtocolStep:
    return ProtocolStep(
        step_number=n, title=title, duration_minutes=dur,
        description=desc, critical_notes=notes, references=refs,
    )


def _mat(name: str, supplier: str, sku: str | None, qty: str, unit: float, total: float) -> Material:
    return Material(
        name=name, catalog_number=sku, supplier=supplier,
        quantity=qty, unit_cost_usd=unit, line_total_usd=total,
    )


# ---------- 1. Diagnostics: paper-based electrochemical CRP biosensor ----------

def crp_biosensor_plan() -> ExperimentPlan:
    parsed = ParsedHypothesis(
        intervention="Paper-based electrochemical biosensor with anti-CRP antibodies",
        measurable_outcome="C-reactive protein concentration in whole blood",
        threshold="<= 0.5 mg/L LoD, time-to-result <= 10 min, sensitivity matching ELISA",
        mechanism="Anti-CRP capture on screen-printed carbon electrode, faradaic readout via [Ru(NH3)6]3+/2+",
        control_condition="Same blood samples measured by laboratory ELISA",
        domain="diagnostics",
        keywords=["CRP biosensor", "electrochemical", "whole blood", "ELISA", "paper microfluidic"],
    )
    return ExperimentPlan(
        title="Paper-based electrochemical CRP biosensor — analytical validation against ELISA",
        domain="diagnostics", hypothesis_summary=(
            "Develop a paper microfluidic SPCE biosensor for CRP in whole blood and validate "
            "LoD, sensitivity, reproducibility and time-to-result against the laboratory ELISA reference."
        ),
        parsed_hypothesis=parsed,
        protocol=[
            _step(1, "Regulatory approval and blood-handling SOP sign-off", 60,
                "File the IRB / IBC amendment for human whole-blood sample handling. Verify BSL-2 lab status, sharps and biohazard waste streams, and operator bloodborne-pathogen training. Hold the kick-off meeting with the lab safety officer to confirm spill response.",
                "Cannot acquire whole blood lots until IRB approval is logged in the LIMS.",
                ["https://www.fda.gov/medical-devices/in-vitro-diagnostics"]),
            _step(2, "SPCE electrochemical pre-treatment", 45,
                "Pre-treat each Metrohm DropSens SPCE in 0.5 M H2SO4 by cyclic voltammetry from -0.4 V to +1.4 V vs Ag pseudo-ref, 50 mV/s, 20 cycles, until peak separation stabilises. Rinse with Milli-Q water, dry under N2.",
                "Skip pre-treatment and the EDC/NHS yield drops by ~40%; cycle until baseline drift < 2% between consecutive sweeps.",
                ["https://dropsens.com/en/screen_printed_electrodes_pag.html"]),
            _step(3, "Antibody immobilization via EDC/NHS chemistry", 120,
                "Activate the SPCE working electrode with 50 mM EDC + 25 mM NHS in MES buffer pH 5.5 for 30 min at 25 °C. Immediately apply 5 µL of 50 µg/mL anti-CRP capture antibody (clone C7) in PBS, incubate 60 min at 25 °C in a humidified chamber, rinse with PBS-T.",
                "EDC half-life in aqueous buffer is ~5 min — couple immediately after activation; avoid using PBS during activation as phosphate quenches NHS.",
                ["https://www.protocols.io/view/edc-nhs-amine-coupling"]),
            _step(4, "BSA blocking", 60,
                "Block the functionalised electrode with 1% (w/v) BSA in PBS, pH 7.4, for 45 min at 25 °C. Wash 3 × with 200 µL PBS-T and once with PBS. Store at 4 °C and use within 24 h.",
                "Under-blocking gives high non-specific binding; over-blocking with > 3% BSA can mask the antibody binding site.",
                []),
            _step(5, "Wax-printed paper microfluidic fabrication", 90,
                "Design hydrophobic-bounded sample, conjugate, and detection zones in CleWin. Print on Whatman Grade 1 with a Xerox ColorQube wax printer and bake at 120 °C for 2 min on a hotplate to wick the wax through the paper thickness.",
                "Bake too long and the wax bleeds laterally, narrowing channels; verify under transmitted light before use.",
                ["https://doi.org/10.1021/ac901071p"]),
            _step(6, "CRP standard ladder in pooled whole blood", 60,
                "Spike pooled lithium-heparin whole blood with recombinant CRP at 0.1, 0.25, 0.5, 1, 2.5, 5, 10, 25, 50 mg/L. Prepare three independent ladders. Aliquot into low-binding tubes and equilibrate to 25 °C for 10 min before assay.",
                "Endogenous CRP in pooled blood must be measured first by ELISA and subtracted from the spike to get a true zero.",
                []),
            _step(7, "Sample application and equilibration", 10,
                "Pipette 20 µL of spiked whole blood onto the sample pad. Wait 2 min for plasma separation through the asymmetric membrane and 1 min for binding equilibration on the working electrode.",
                "Inadequate equilibration causes negative bias at low CRP; standardise the wait via a built-in capillary fill-time indicator.",
                []),
            _step(8, "Square-wave voltammetry acquisition", 5,
                "Run SWV from -0.5 V to +0.1 V vs Ag pseudo-ref, frequency 25 Hz, amplitude 25 mV, step 4 mV, in the presence of 1 mM [Ru(NH3)6]Cl3 mediator. Record peak current at the redox potential of the mediator.",
                "Scan rate above 50 Hz collapses the diffusion layer and inflates the signal nonlinearly.",
                []),
            _step(9, "Calibration fit and LoD estimation", 60,
                "Fit the peak current vs CRP concentration with a 4-parameter logistic model in OriginPro 2024. Compute LoD as 3·σ_blank / slope using six replicate blanks. Cross-check linear range by Mandel's fitting test.",
                "Report LoD with the actual blank distribution, not the LLOQ from the fit.",
                []),
            _step(10, "ELISA reference measurement", 240,
                "Run R&D Systems DCRP00 ELISA on the same 30 paired whole-blood samples, blinded labelling. Use the Tecan Spark plate reader at 450 nm with 540 nm reference subtraction. Plate layout pre-randomised per CLSI EP09-A3.",
                "Run all 30 samples on the same plate to remove plate-to-plate variance; if forced to split, include three QC samples per plate.",
                ["https://www.rndsystems.com/products/human-c-reactive-protein-quantikine-elisa-kit_dcrp00"]),
            _step(11, "Method comparison and clinical sensitivity", 90,
                "Compare biosensor vs ELISA by Deming regression and Bland-Altman analysis (95% LoA). Compute clinical sensitivity at the 1 mg/L cardiovascular risk cut-off. Run McNemar's test for paired classification agreement.",
                "Use Deming, not OLS — both methods carry measurement error.",
                []),
            _step(12, "Inter-electrode reproducibility study", 180,
                "Test 20 independent SPCEs on a single mid-range CRP sample (3 mg/L). Report inter-electrode CV. Use a one-way ANOVA on ranks to flag any electrode batch with outlier behaviour.",
                "Pre-screen each SPCE by 1 mM ferricyanide redox; reject any with deviation > 10% from batch mean before functionalisation.",
                []),
        ],
        materials=[
            _mat("Anti-CRP capture antibody (mouse mAb, clone C7)", "Thermo Fisher", "MA1-91256", "100 µg", 380.0, 380.0),
            _mat("Anti-CRP detection antibody (rabbit pAb)", "Abcam", "ab31156", "100 µg", 420.0, 420.0),
            _mat("Recombinant human C-reactive protein", "Sigma-Aldrich", "C4063", "1 mg", 280.0, 280.0),
            _mat("Whatman Grade 1 filter paper", "Sigma-Aldrich", "WHA1001824", "100 sheets", 95.0, 95.0),
            _mat("Screen-printed carbon electrodes (SPCE)", "Metrohm", "DRP-110", "50 ct", 340.0, 680.0),
            _mat("EDC/NHS amine-coupling kit", "Thermo Fisher", "22980", "1 kit", 140.0, 140.0),
            _mat("Bovine Serum Albumin, fraction V", "Sigma-Aldrich", "A7906", "50 g", 110.0, 110.0),
            _mat("PBS tablets, pH 7.4", "Sigma-Aldrich", "P4417", "100 tablets", 48.0, 48.0),
            _mat("Hexaammineruthenium(III) chloride", "Sigma-Aldrich", "262005", "1 g", 95.0, 95.0),
            _mat("Pooled human whole blood, Li-heparin", "Innovative Research", "IWB1K2EK2", "10 mL", 185.0, 555.0),
            _mat("Disposable safety lancets", "Greiner Bio-One", "450290", "100 ct", 72.0, 72.0),
            _mat("Potentiostat access (PalmSens4 or Autolab)", "Core facility", None, "80 hr", 20.0, 1600.0),
            _mat("Wax printing & lamination access", "Core facility", None, "1 setup", 220.0, 220.0),
            _mat("Human CRP ELISA reference kit", "R&D Systems", "DCRP00", "1 kit", 520.0, 520.0),
        ],
        total_budget_usd=0.0,  # recomputed by validation.normalize_plan
        currency="USD",
        timeline=[
            TimelinePhase(phase_name="Phase 0: Procurement, IRB, training",
                          duration_weeks=3.0, dependencies=[],
                          deliverables=["IRB approval", "all reagents on-bench", "operator BBP training cert."]),
            TimelinePhase(phase_name="Phase 1: SPCE functionalisation optimisation",
                          duration_weeks=2.0, dependencies=["Phase 0: Procurement, IRB, training"],
                          deliverables=["locked EDC/NHS protocol", "blocking SOP"]),
            TimelinePhase(phase_name="Phase 2: Calibration and analytical validation",
                          duration_weeks=2.0, dependencies=["Phase 1: SPCE functionalisation optimisation"],
                          deliverables=["4-PL calibration curve", "LoD report"]),
            TimelinePhase(phase_name="Phase 3: Whole-blood method comparison vs ELISA",
                          duration_weeks=2.0, dependencies=["Phase 2: Calibration and analytical validation"],
                          deliverables=["Bland-Altman plot", "Deming regression"]),
            TimelinePhase(phase_name="Phase 4: Inter-electrode reproducibility & report",
                          duration_weeks=1.0, dependencies=["Phase 3: Whole-blood method comparison vs ELISA"],
                          deliverables=["CV across 20 SPCEs", "manuscript draft"]),
        ],
        total_duration_weeks=10.0,
        validation=[
            ValidationMetric(metric="Limit of detection (LoD)",
                             success_threshold="<= 0.5 mg/L (3·σ_blank/slope, n = 6 blanks)",
                             measurement_method="4-PL fit on serial-dilution series in pooled blood, OriginPro 2024"),
            ValidationMetric(metric="Method agreement vs ELISA",
                             success_threshold="Pearson r >= 0.95, mean bias <= 0.3 mg/L (n = 30 paired)",
                             measurement_method="Deming regression and Bland-Altman 95% LoA per CLSI EP09-A3"),
            ValidationMetric(metric="Inter-electrode reproducibility",
                             success_threshold="CV <= 15% across 20 SPCEs at 3 mg/L",
                             measurement_method="One-way ANOVA on ranks, 95% CI by bootstrap (10k)"),
            ValidationMetric(metric="Time-to-result",
                             success_threshold="<= 10 min, 95% CI <= 11 min (n = 30)",
                             measurement_method="Stopwatch + capillary fill indicator, mean and 95% CI"),
            ValidationMetric(metric="Spiked recovery in whole blood",
                             success_threshold="90-110% recovery at 0.5, 2, 10 mg/L (n = 18)",
                             measurement_method="Standard addition, ANOVA with Tukey HSD"),
        ],
        risks_and_mitigations=[
            "Hemoglobin / lipid interference suppresses signal at low CRP. Mitigation: integrate an asymmetric plasma-separation membrane (Vivid GR) and pre-validate against haemolysed and lipaemic spike-ins.",
            "Antibody lot-to-lot variability shifts the calibration curve. Mitigation: lock a single lot for the full study, qualify it by SPR Kd, and bank > 6-month supply.",
            "SPCE batch CV exceeds 15%. Mitigation: pre-screen each electrode by 1 mM ferricyanide redox and reject any with > 10% deviation from batch mean.",
            "Recombinant CRP standard degrades on freeze-thaw. Mitigation: aliquot into single-use 50 µL tubes, store at -80 °C, log thaw count.",
            "IRB amendment delayed past procurement window. Mitigation: parallel-track buffer optimisation and SPCE pre-treatment, which need no human samples.",
        ],
        applied_corrections=[],
    )


# ---------- 2. Gut Health: Lactobacillus rhamnosus GG in C57BL/6 mice ----------

def lactobacillus_gut_plan() -> ExperimentPlan:
    parsed = ParsedHypothesis(
        intervention="Daily oral gavage of Lactobacillus rhamnosus GG (LGG) for 4 weeks",
        measurable_outcome="Intestinal permeability via FITC-dextran serum concentration",
        threshold=">= 30% reduction vs vehicle control, p < 0.05, n = 12 per arm",
        mechanism="Upregulation of tight-junction proteins claudin-1 and occludin",
        control_condition="Vehicle (MRS broth) gavage in age- and sex-matched C57BL/6 mice",
        domain="gut_health",
        keywords=["Lactobacillus rhamnosus GG", "FITC-dextran", "claudin-1", "occludin", "C57BL/6"],
    )
    return ExperimentPlan(
        title="LGG supplementation reduces intestinal permeability in C57BL/6 mice — 4-week trial",
        domain="gut_health", hypothesis_summary=(
            "A randomised, controlled, parallel-arm study in C57BL/6 mice testing whether 4 weeks of daily "
            "LGG gavage reduces FITC-dextran flux and upregulates tight-junction proteins."
        ),
        parsed_hypothesis=parsed,
        protocol=[
            _step(1, "IACUC protocol approval and animal sourcing", 60,
                "Submit IACUC amendment covering oral gavage, FITC-dextran administration, and terminal blood collection. Order C57BL/6J mice (8-10 wk, female and male, n = 24/sex/arm + 10% attrition) from Jackson Laboratory and acclimatise for 7 days under 12:12 light cycle.",
                "Animals not acclimatised >= 7 days produce inflated baseline permeability variance.",
                ["https://www.jax.org/strain/000664"]),
            _step(2, "LGG culture and viability counting", 90,
                "Streak Lactobacillus rhamnosus GG ATCC 53103 onto MRS agar, pick a single colony, expand in MRS broth at 37 °C anaerobic for 18 h. Pellet, wash twice in PBS, resuspend in MRS broth at 1 × 10^9 CFU/mL. Verify CFU by plating dilutions in triplicate.",
                "Glycerol stocks lose 0.5-1 log per freeze-thaw — restreak for every batch.",
                ["https://www.atcc.org/products/53103"]),
            _step(3, "Randomisation and blinding", 30,
                "Randomise mice to LGG vs vehicle within sex and cage using a stratified block randomisation (R 4.4, blockrand). Generate blinded animal IDs; gavage operator and outcome assessor see only the IDs.",
                "Cage effects bias permeability — randomise within cage, not just within arm.",
                []),
            _step(4, "Daily oral gavage for 28 days", 5,
                "Deliver 200 µL of LGG suspension (2 × 10^8 CFU) or 200 µL of MRS broth vehicle by oral gavage with a 20 G stainless feeding needle once daily at 09:00 ± 1 h for 28 consecutive days. Body weight recorded every other day.",
                "Aspiration risk — practice gavage technique on non-experimental cull mice first.",
                ["https://www.protocols.io/view/oral-gavage-in-mice"]),
            _step(5, "Weekly faecal sampling and 16S sequencing", 60,
                "Collect fresh faecal pellets weekly. Extract DNA with Qiagen DNeasy PowerSoil Pro. Amplify V3-V4 with Illumina-compatible primers and sequence on a MiSeq (2 × 300 bp). Confirm LGG colonisation by qPCR with strain-specific primers.",
                "qPCR primers must distinguish LGG from endogenous L. rhamnosus — validate against type strain and a vehicle-arm sample.",
                ["https://www.qiagen.com/us/products/discovery-and-translational-research/dna-rna-purification/dna-purification/genomic-dna/dneasy-powersoil-pro-kit"]),
            _step(6, "FITC-dextran administration on day 28", 10,
                "Fast mice 4 h, then administer 4 kDa FITC-dextran by gavage at 600 mg/kg in PBS. Time-zero blood collection from tail vein (10 µL) before dosing as autofluorescence baseline.",
                "Use 4 kDa, not 70 kDa — 70 kDa underestimates barrier loss in early-stage permeability changes.",
                ["https://doi.org/10.1038/nprot.2007.521"]),
            _step(7, "Terminal serum collection and FITC quantification", 90,
                "4 h post-dosing, anaesthetise with isoflurane, collect blood by cardiac puncture, allow 30 min clot at RT, centrifuge 2000 g × 10 min for serum. Measure FITC fluorescence on a Tecan Spark plate reader (excitation 485 nm, emission 528 nm) against a standard curve in pooled mouse serum.",
                "Serum haemolysis quenches FITC fluorescence — flag any sample with absorbance at 414 nm > 0.5 and re-collect if possible.",
                []),
            _step(8, "Tissue harvest for tight-junction analysis", 90,
                "Excise 2 cm of distal ileum; flush with PBS; split for (a) snap-freeze in liquid N2 (Western), (b) fix in 10% NBF (IHC), and (c) RNA later for qPCR. Maintain tissue ID linkage to blinded animal ID.",
                "Tissue collection order matters — snap-freeze section first; transcripts degrade fast at room temp.",
                []),
            _step(9, "Western blot for claudin-1 and occludin", 240,
                "Lyse 30 mg of distal ileum in RIPA + protease inhibitors. Run 30 µg per lane on 12% SDS-PAGE, transfer to PVDF, probe with anti-claudin-1 (Invitrogen 51-9000) and anti-occludin (Invitrogen 71-1500). Normalise to GAPDH; quantify by Image Studio.",
                "Claudin-1 antibodies cross-react with claudin-3 — validate with a knockout lysate or use a clone with documented specificity.",
                []),
            _step(10, "qPCR for tight-junction transcripts", 180,
                "Extract RNA with Qiagen RNeasy. Reverse transcribe with Bio-Rad iScript. Run qPCR for Cldn1, Ocln, Tjp1 with PrimeTime IDT primers; normalise to Hprt and B2m geometric mean per MIQE.",
                "Use two reference genes minimum; single-gene normalisation underestimates variance.",
                ["https://academic.oup.com/clinchem/article/55/4/611/5631762"]),
            _step(11, "Histology and barrier scoring", 240,
                "Process NBF-fixed ileum to paraffin, 5 µm sections, H&E and IHC for claudin-1 and occludin. Score by a histologist blinded to arm using a 0-4 inflammation scale and apical claudin-1 continuity index.",
                "Histologist must be blinded; arm assignment leaking into scoring is the most common source of false positives in this assay.",
                []),
            _step(12, "Statistical analysis and multiplicity control", 120,
                "Primary endpoint: serum FITC concentration, two-sided Welch's t-test, alpha = 0.05. Secondary: claudin-1 and occludin Western band intensity, two-sided Mann-Whitney with Bonferroni-Holm correction. Pre-register the analysis plan on OSF before unblinding.",
                "Pre-registration is the single biggest defence against post hoc rescue analyses.",
                []),
        ],
        materials=[
            _mat("C57BL/6J mice, 8-10 wk", "Jackson Laboratory", "000664", "60 mice", 38.0, 2280.0),
            _mat("LGG type strain", "ATCC", "53103", "1 vial", 410.0, 410.0),
            _mat("MRS broth", "Sigma-Aldrich", "69966", "500 g", 220.0, 220.0),
            _mat("FITC-dextran 4 kDa", "Sigma-Aldrich", "46944", "1 g", 165.0, 165.0),
            _mat("DNeasy PowerSoil Pro Kit", "Qiagen", "47014", "50 preps", 460.0, 460.0),
            _mat("RNeasy Mini Kit", "Qiagen", "74104", "50 preps", 380.0, 380.0),
            _mat("iScript cDNA Synthesis Kit", "Bio-Rad", "1708890", "100 rxns", 320.0, 320.0),
            _mat("Anti-claudin-1 antibody", "Invitrogen", "51-9000", "100 µg", 380.0, 380.0),
            _mat("Anti-occludin antibody", "Invitrogen", "71-1500", "100 µg", 380.0, 380.0),
            _mat("PrimeTime qPCR primer/probe sets", "IDT", "Custom", "6 assays", 95.0, 570.0),
            _mat("Stainless feeding needles, 20 G", "Fisher Scientific", "01-208-87", "10 ct", 165.0, 165.0),
            _mat("MiSeq run access (2 × 300 bp)", "Core facility", None, "1 run", 1800.0, 1800.0),
            _mat("Histology service (paraffin + IHC)", "Core facility", None, "60 blocks", 18.0, 1080.0),
            _mat("Per-diem animal housing fees", "Vivarium", None, "60 mice × 35 d", 0.85, 1785.0),
        ],
        total_budget_usd=0.0,
        currency="USD",
        timeline=[
            TimelinePhase(phase_name="Phase 0: IACUC, sourcing, acclimatisation",
                          duration_weeks=4.0, dependencies=[],
                          deliverables=["IACUC approval", "mice acclimatised", "LGG culture banked"]),
            TimelinePhase(phase_name="Phase 1: 28-day daily gavage",
                          duration_weeks=4.0, dependencies=["Phase 0: IACUC, sourcing, acclimatisation"],
                          deliverables=["body-weight log", "weekly faecal samples", "colonisation qPCR"]),
            TimelinePhase(phase_name="Phase 2: Permeability assay and tissue harvest",
                          duration_weeks=1.0, dependencies=["Phase 1: 28-day daily gavage"],
                          deliverables=["serum FITC values", "ileum tissue banked"]),
            TimelinePhase(phase_name="Phase 3: Tight-junction Western, qPCR, histology",
                          duration_weeks=3.0, dependencies=["Phase 2: Permeability assay and tissue harvest"],
                          deliverables=["claudin-1 / occludin band intensities", "Cldn1/Ocln/Tjp1 qPCR Cq table", "blinded histology scores"]),
            TimelinePhase(phase_name="Phase 4: Statistics, manuscript",
                          duration_weeks=2.0, dependencies=["Phase 3: Tight-junction Western, qPCR, histology"],
                          deliverables=["pre-registered analysis", "manuscript draft"]),
        ],
        total_duration_weeks=14.0,
        validation=[
            ValidationMetric(metric="Primary endpoint: serum FITC-dextran",
                             success_threshold=">= 30% reduction, p < 0.05, n = 12 per arm",
                             measurement_method="Welch's t-test on log-transformed concentrations, R 4.4"),
            ValidationMetric(metric="Claudin-1 protein expression",
                             success_threshold=">= 1.5x band intensity vs vehicle, p < 0.05",
                             measurement_method="Western blot densitometry (Image Studio), Mann-Whitney with Bonferroni-Holm"),
            ValidationMetric(metric="Occludin protein expression",
                             success_threshold=">= 1.3x band intensity vs vehicle, p < 0.05",
                             measurement_method="Western blot densitometry, Mann-Whitney with Bonferroni-Holm"),
            ValidationMetric(metric="LGG colonisation",
                             success_threshold=">= 10^6 CFU/g faeces by week 2, sustained through week 4 (n = 12)",
                             measurement_method="Strain-specific qPCR on faecal DNA, Cq vs CFU standard curve"),
            ValidationMetric(metric="Histological barrier scoring",
                             success_threshold="Apical claudin-1 continuity index >= 0.8 (vs vehicle 0.55), blinded scorer",
                             measurement_method="IHC, 0-1 continuity score on 10 high-power fields per animal"),
        ],
        risks_and_mitigations=[
            "Cage effect dominates between-animal variance. Mitigation: randomise within cage and treat cage as random effect in a mixed model sensitivity analysis.",
            "FITC-dextran autofluorescence in haemolysed serum biases readouts. Mitigation: pre-screen at 414 nm and exclude samples with absorbance > 0.5; collect a fresh sample where possible.",
            "Sex-specific permeability differences hide a real effect when pooled. Mitigation: power for n = 12/sex/arm and pre-register sex-stratified analysis.",
            "Antibody cross-reactivity between claudin-1 and -3. Mitigation: orthogonal qPCR for Cldn1; consider a knockout lysate control.",
            "Animal attrition above 10%. Mitigation: enrol +10% buffer at the start; protocol allows backfill within first week of dosing only.",
        ],
        applied_corrections=[],
    )


# ---------- 3. Cell Biology: trehalose vs DMSO cryoprotection of HeLa cells ----------

def trehalose_cryo_plan() -> ExperimentPlan:
    parsed = ParsedHypothesis(
        intervention="Trehalose-based freezing medium (replacing sucrose, compared to standard DMSO)",
        measurable_outcome="Post-thaw viability of HeLa cells",
        threshold=">= 15 percentage point increase vs DMSO standard",
        mechanism="Trehalose membrane stabilisation at low temperature",
        control_condition="10% DMSO + FBS standard freezing protocol",
        domain="cell_biology",
        keywords=["trehalose", "DMSO", "cryoprotection", "HeLa", "post-thaw viability"],
    )
    return ExperimentPlan(
        title="Trehalose vs DMSO cryoprotection of HeLa cells — head-to-head viability and recovery study",
        domain="cell_biology",
        hypothesis_summary=(
            "Compare post-thaw viability, attachment, and proliferation of HeLa cells frozen in three media: "
            "10% DMSO (gold standard), 10% sucrose, and 0.2 M trehalose, with replicates across three passages."
        ),
        parsed_hypothesis=parsed,
        protocol=[
            _step(1, "Cell line authentication and mycoplasma screen", 60,
                "Confirm HeLa identity by STR profiling at the institutional core (DDC Medical or ATCC). Screen for mycoplasma by MycoAlert at receipt and weekly during expansion. Document negative result before proceeding.",
                "STR-mismatched HeLa stocks are a known reproducibility crisis source; do not skip this.",
                ["https://www.atcc.org/services/services/cell-line-authentication-services"]),
            _step(2, "Cell expansion and synchronisation", 240,
                "Thaw a single-passage stock, plate in DMEM + 10% FBS + 1% pen/strep, expand to 80% confluence over 3 passages. Use only passage P + 2 to P + 5 from this thaw.",
                "Late-passage HeLa shifts viability response — strict passage window matters.",
                []),
            _step(3, "Freezing-medium preparation", 60,
                "Prepare three media on ice: (a) 10% DMSO + 90% FBS, (b) 10% sucrose in FBS, (c) 0.2 M trehalose in 5% DMSO + FBS. Sterile filter (0.22 µm). Pre-chill cryovials.",
                "DMSO is exothermic in solution — mix on ice and use within 4 h.",
                ["https://www.sigmaaldrich.com/US/en/technical-documents/protocol/cell-culture-and-cell-culture-analysis/cell-culture-protocols/cryopreservation"]),
            _step(4, "Harvest, count, normalise to seeding density", 30,
                "Trypsinise at 80% confluence with 0.05% trypsin-EDTA, neutralise 1:1 in DMEM + 10% FBS, count by Vi-Cell XR, adjust to 1 × 10^6 cells/mL in each freezing medium.",
                "Over-trypsinisation is the silent confounder — keep to <= 5 min and use a fixed passage operator.",
                []),
            _step(5, "Controlled-rate freezing", 120,
                "Aliquot 1 mL per cryovial in triplicate per condition. Place in a Mr Frosty (1 °C/min) at -80 °C overnight, then transfer to vapour-phase liquid nitrogen.",
                "Skip Mr Frosty and ice nucleation becomes random; viability variance doubles.",
                ["https://www.thermofisher.com/order/catalog/product/5100-0001"]),
            _step(6, "Storage period", 30,
                "Store cryovials in vapour-phase LN2 for >= 7 days. Log temperature daily (LN2 dewar logger). 7 days is the minimum required to model long-term storage stress.",
                "Do not test at 24 h post-freeze; that under-stresses the system and overstates viability.",
                []),
            _step(7, "Rapid thaw and dilution", 15,
                "Thaw in a 37 °C water bath, swirling, until the last ice crystal melts (~90 s). Immediately dilute 1:10 in pre-warmed DMEM + 10% FBS to dilute DMSO. Centrifuge 200 g × 5 min, resuspend in fresh medium.",
                "Slow thaw kills cells; don't leave the vial above 4 °C until ready to dilute.",
                []),
            _step(8, "Trypan blue and acridine orange viability", 30,
                "Run trypan blue exclusion on the Vi-Cell XR for total viability. Run AO/PI on the Nexcelom Cellometer for live/dead in the same sample. Triplicate technical reads per cryovial.",
                "Trypan blue alone over-counts dead cells in DMSO — pair with AO/PI.",
                ["https://www.nexcelom.com/applications/ao-pi-viability/"]),
            _step(9, "Re-attachment assay at 4 h and 24 h", 240,
                "Plate 1 × 10^5 cells per well in a 12-well plate (n = 6 wells per condition). Image at 4 h and 24 h on an IncuCyte; quantify confluence and rounded-cell ratio. Recover same wells for proliferation curve.",
                "Cells with ruptured membranes attach but fail to spread — log spread morphology, not just attachment.",
                []),
            _step(10, "72-h proliferation curve and doubling time",
                  240,
                "Continue IncuCyte imaging at 4-h intervals for 72 h. Fit exponential growth in GraphPad Prism 10; compute doubling time per well.",
                "If doubling time exceeds the parental stock by > 30%, flag the cryomedium even if 24-h viability passes.",
                []),
            _step(11, "Membrane integrity by lactate dehydrogenase release", 60,
                "Collect 50 µL supernatant at 4 h post-thaw. Run Promega CytoTox 96 LDH assay. Higher LDH = greater plasma membrane damage independent of trypan blue.",
                "LDH has 6 h half-life in serum-containing medium — sample early.",
                ["https://www.promega.com/products/cell-health-assays/cell-viability-and-cytotoxicity-assays/cytotox-96-non_radioactive-cytotoxicity-assay/"]),
            _step(12, "Statistics and multiplicity",
                  90,
                "Primary endpoint: 24-h trypan-blue viability difference (trehalose - DMSO). Use Welch's t-test with effect size (Cohen's d). Secondary endpoints: doubling time and LDH; Bonferroni-Holm correction across the 3 secondaries. Pre-register on OSF.",
                "Pre-register to prevent the well-known cryomedia post-hoc-shopping problem.",
                []),
        ],
        materials=[
            _mat("HeLa cells, authenticated", "ATCC", "CCL-2", "1 vial", 595.0, 595.0),
            _mat("DMEM, high glucose", "Thermo Fisher", "11965092", "500 mL", 26.0, 78.0),
            _mat("Fetal Bovine Serum, qualified", "Thermo Fisher", "26140079", "500 mL", 580.0, 580.0),
            _mat("Penicillin-Streptomycin", "Thermo Fisher", "15140122", "100 mL", 38.0, 38.0),
            _mat("Trehalose dihydrate", "Sigma-Aldrich", "T9531", "100 g", 95.0, 95.0),
            _mat("Sucrose, cell culture grade", "Sigma-Aldrich", "S1888", "500 g", 78.0, 78.0),
            _mat("DMSO, Hybri-Max sterile-filtered", "Sigma-Aldrich", "D2650", "100 mL", 110.0, 110.0),
            _mat("Trypsin-EDTA 0.05%", "Thermo Fisher", "25300054", "500 mL", 32.0, 64.0),
            _mat("Cryovials, 1.8 mL", "Thermo Fisher", "377267", "100 ct", 86.0, 172.0),
            _mat("Mr Frosty freezing container", "Thermo Fisher", "5100-0001", "1 unit", 92.0, 92.0),
            _mat("CytoTox 96 Non-Radioactive LDH kit", "Promega", "G1780", "1 kit", 360.0, 360.0),
            _mat("AO/PI viability reagent", "Nexcelom", "CS2-0106-5mL", "5 mL", 240.0, 240.0),
            _mat("12-well plates, TC-treated", "Thermo Fisher", "150628", "100 ct", 145.0, 145.0),
            _mat("IncuCyte access fee", "Core facility", None, "120 hr", 6.0, 720.0),
            _mat("STR authentication service", "Core facility", None, "1 sample", 240.0, 240.0),
        ],
        total_budget_usd=0.0,
        currency="USD",
        timeline=[
            TimelinePhase(phase_name="Phase 0: Authentication and expansion",
                          duration_weeks=2.0, dependencies=[],
                          deliverables=["STR pass", "mycoplasma negative", "P+2 working stock"]),
            TimelinePhase(phase_name="Phase 1: Freezing and storage",
                          duration_weeks=2.0, dependencies=["Phase 0: Authentication and expansion"],
                          deliverables=["all cryovials in vapour-phase LN2", "freezing log"]),
            TimelinePhase(phase_name="Phase 2: Thaw and viability assays",
                          duration_weeks=2.0, dependencies=["Phase 1: Freezing and storage"],
                          deliverables=["trypan + AO/PI viability table", "LDH assay results"]),
            TimelinePhase(phase_name="Phase 3: Recovery and proliferation",
                          duration_weeks=2.0, dependencies=["Phase 2: Thaw and viability assays"],
                          deliverables=["72-h IncuCyte proliferation curves", "doubling-time table"]),
            TimelinePhase(phase_name="Phase 4: Stats and write-up",
                          duration_weeks=1.0, dependencies=["Phase 3: Recovery and proliferation"],
                          deliverables=["pre-registered analysis", "manuscript draft"]),
        ],
        total_duration_weeks=9.0,
        validation=[
            ValidationMetric(metric="Primary endpoint: 24-h post-thaw viability (trypan blue)",
                             success_threshold=">= 15 pp gain trehalose vs DMSO, p < 0.05, n = 9 vials/arm",
                             measurement_method="Welch's t-test, Cohen's d, Vi-Cell XR average of 3 reads"),
            ValidationMetric(metric="Membrane integrity by LDH release",
                             success_threshold="<= 0.7x DMSO LDH signal at 4 h, p < 0.05",
                             measurement_method="Promega CytoTox 96 assay, Mann-Whitney with Bonferroni-Holm"),
            ValidationMetric(metric="Re-attachment at 24 h",
                             success_threshold=">= 80% confluence, indistinguishable from DMSO (95% CI overlapping)",
                             measurement_method="IncuCyte phase-contrast confluence quantification"),
            ValidationMetric(metric="Doubling time over 72 h",
                             success_threshold="Within 1.3x of unfrozen control (n = 6 wells)",
                             measurement_method="Exponential fit in GraphPad Prism 10"),
            ValidationMetric(metric="Cross-passage robustness",
                             success_threshold="Effect size preserved across passages P+2, P+3, P+4",
                             measurement_method="Two-way ANOVA on viability with passage and condition as factors"),
        ],
        risks_and_mitigations=[
            "Mycoplasma contamination after expansion. Mitigation: weekly MycoAlert; sentinel well test before freeze; discard whole stock on positive.",
            "Operator-to-operator trypsinisation variance. Mitigation: lock a single operator, fix incubation time to 4 min, log every harvest.",
            "Trehalose membrane permeability is low without a permeabiliser. Mitigation: include a 5% DMSO co-medium and a separate hypotonic-loading arm to bracket the answer.",
            "LN2 dewar warming event. Mitigation: pair the dewar with a daily logger and a SMS-alert level sensor; keep a backup LN2 stock.",
            "Cell-line drift between freeze and thaw. Mitigation: bank a parallel unfrozen plate at the freeze step and benchmark the post-thaw plate against it.",
        ],
        applied_corrections=[],
    )


# ---------- 4. Climate: Sporomusa ovata bioelectrochemical CO2 fixation ----------

def sporomusa_co2_plan() -> ExperimentPlan:
    parsed = ParsedHypothesis(
        intervention="Sporomusa ovata at cathode poised at -400 mV vs SHE in a bioelectrochemical system",
        measurable_outcome="Acetate production rate from CO2",
        threshold=">= 150 mmol/L/day, >= 20% over current biocatalytic carbon-capture benchmark",
        mechanism="Direct electron transfer from cathode to S. ovata supports CO2 reduction to acetate",
        control_condition="Open-circuit cell with same medium and biomass",
        domain="climate",
        keywords=["Sporomusa ovata", "bioelectrochemistry", "CO2 fixation", "acetate", "cathode"],
    )
    return ExperimentPlan(
        title="Sporomusa ovata CO2-to-acetate at -400 mV — rate, coulombic efficiency, and stability",
        domain="climate",
        hypothesis_summary=(
            "Build a two-chamber H-cell bioelectrochemical reactor, inoculate with S. ovata DSM 2662, hold the "
            "cathode at -400 mV vs SHE, and quantify acetate production rate, coulombic efficiency, and 14-day stability."
        ),
        parsed_hypothesis=parsed,
        protocol=[
            _step(1, "Reactor build and leak test", 240,
                "Assemble a custom two-chamber H-cell with Nafion 117 membrane between cathode and anode chambers (working volume 250 mL each). Pressure-test with N2 at 0.5 bar overnight. Polish the carbon felt cathode with HCl and rinse to neutral.",
                "A pinhole in Nafion crashes coulombic efficiency by O2 crossover; never skip the leak test.",
                ["https://www.fuelcellstore.com/nafion-117"]),
            _step(2, "S. ovata revival and pre-culture", 240,
                "Revive DSM 2662 from glycerol stock in DSMZ medium 311 (modified) anaerobically with H2/CO2 80:20 at 30 °C for 7 days. Confirm purity by 16S Sanger and microscopy.",
                "Sporomusa is fastidious — verify anaerobic seal on every transfer (resazurin indicator).",
                ["https://www.dsmz.de/microorganisms/medium/pdf/DSMZ_Medium311.pdf"]),
            _step(3, "Cathode chamber inoculation",
                  60,
                "Transfer 25 mL of mid-log pre-culture (OD600 ~0.4) into the cathode chamber pre-flushed with N2/CO2 80:20. Hold at 30 °C with magnetic stirring at 200 rpm.",
                "Inoculation under air destroys CO2 fixation enzymes; transfer through a butyl-stoppered crimp port.",
                []),
            _step(4, "Cathode poise at -400 mV vs SHE", 60,
                "Connect the cathode to a Gamry Reference 600+ potentiostat in chronoamperometry mode at -400 mV vs Ag/AgCl (sat. KCl) reference, equivalent to ~ -403 mV vs SHE after correction. Anode is a Pt mesh in 100 mM phosphate buffer.",
                "Reference electrode drift > 5 mV invalidates the experiment; re-calibrate weekly with a freshly prepared standard.",
                []),
            _step(5, "Daily liquid sampling and acetate quantification", 30,
                "Withdraw 1 mL through the sample port, filter (0.22 µm), and inject 10 µL onto an HPLC with an Aminex HPX-87H column and refractive-index detector. Quantify acetate against a 0.1 - 50 mM calibration.",
                "HPX-87H column degrades fast on aged sulphuric acid mobile phase — replace mobile phase weekly.",
                ["https://www.bio-rad.com/en-us/sku/1250140-aminex-hpx-87h-column-300-x-7-8-mm"]),
            _step(6, "Headspace sampling for H2, CO2, and CH4",
                  30,
                "Take 250 µL of headspace through the gas-tight sample port and inject into a SRI 8610C GC with TCD/FID. Quantify H2, CO2, and any CH4 against certified gas standards.",
                "If CH4 appears, methanogen contamination is consuming acetate — heat-treat or restart with a fresh inoculum.",
                []),
            _step(7, "Coulombic efficiency calculation", 60,
                "Integrate cathodic current over each 24-h interval to obtain electrons delivered. Convert acetate produced (mol) to electron equivalents (8 e- per acetate). CE = electrons in acetate / total electrons delivered × 100%.",
                "Hydrogen evolution at the cathode parasitises the current — track H2 in headspace and report CE per product.",
                []),
            _step(8, "Biomass and viability tracking",
                  60,
                "Track OD600 daily; quantify biomass dry weight at day 0, 7, and 14 by filtering 5 mL onto a pre-weighed 0.22 µm membrane and drying at 105 °C overnight.",
                "Biofilm on the cathode is real biomass — include it in the day-14 dry weight by sonicating the cathode in PBS.",
                []),
            _step(9, "14-day continuous operation",
                  60,
                "Run the cell for 14 consecutive days. Replace medium every 7 days using a 50% medium swap to keep nutrients in range without disturbing the biofilm.",
                "Full medium swaps wipe the biofilm; keep them partial.",
                []),
            _step(10, "Stability and rate calculation",
                  60,
                "Compute daily volumetric acetate productivity (mmol/L/day) by linear regression on each 24-h window. Report 14-day mean and slope (drift over time).",
                "If slope is significantly negative, biofilm fouling is overtaking productivity — note for the discussion.",
                []),
            _step(11, "Cathode microbial community check",
                  240,
                "At day 14, harvest the cathode biofilm. Extract DNA, sequence 16S V3-V4 on an Illumina MiSeq, and confirm S. ovata > 95% relative abundance with no methanogens.",
                "Acetogen-methanogen co-cultures in BES are common — purity drops fast under stress.",
                []),
            _step(12, "Statistics and benchmark comparison",
                  90,
                "Compare 14-day mean rate against the published 96 mmol/L/day benchmark (Nevin et al., mBio 2010) using a one-sample t-test with a 20% margin (target 115.2). Run sensitivity analysis on cathode potential variance.",
                "Bench numbers vary by reactor geometry; use volumetric productivity normalised to cathode area when comparing.",
                ["https://doi.org/10.1128/mBio.00103-10"]),
        ],
        materials=[
            _mat("Sporomusa ovata DSM 2662", "DSMZ", "DSM-2662", "1 vial", 290.0, 290.0),
            _mat("Carbon felt cathode, 5 mm", "Fuel Cell Store", "CF-5MM", "10 sheets", 28.0, 280.0),
            _mat("Nafion 117 membrane", "Fuel Cell Store", "N117", "1 m^2", 380.0, 380.0),
            _mat("Pt mesh anode", "Sigma-Aldrich", "298093", "10 cm^2", 195.0, 195.0),
            _mat("Ag/AgCl reference electrode", "BASi", "MF-2079", "1 unit", 240.0, 240.0),
            _mat("Gamry Reference 600+ potentiostat access", "Core facility", None, "350 hr", 8.0, 2800.0),
            _mat("DSMZ medium 311 components (vitamins, salts)", "Sigma-Aldrich", "Various", "1 batch", 320.0, 320.0),
            _mat("Sodium 2-bromoethanesulfonate (methanogen inhibitor)", "Sigma-Aldrich", "B7280", "25 g", 145.0, 145.0),
            _mat("Resazurin sodium salt", "Sigma-Aldrich", "R7017", "25 g", 95.0, 95.0),
            _mat("Aminex HPX-87H HPLC column", "Bio-Rad", "1250140", "1 column", 1850.0, 1850.0),
            _mat("HPLC + RID access", "Core facility", None, "60 hr", 28.0, 1680.0),
            _mat("SRI 8610C GC access", "Core facility", None, "30 hr", 22.0, 660.0),
            _mat("Certified gas standard (H2/CO2/CH4)", "Airgas", "X02NI99C2003319", "1 cylinder", 380.0, 380.0),
            _mat("MiSeq run access", "Core facility", None, "1 lane", 1800.0, 1800.0),
        ],
        total_budget_usd=0.0,
        currency="USD",
        timeline=[
            TimelinePhase(phase_name="Phase 0: Reactor build, S. ovata revival",
                          duration_weeks=3.0, dependencies=[],
                          deliverables=["leak-tested H-cell", "pure S. ovata pre-culture"]),
            TimelinePhase(phase_name="Phase 1: Inoculation and ramp-up",
                          duration_weeks=1.0, dependencies=["Phase 0: Reactor build, S. ovata revival"],
                          deliverables=["stable cathodic current at -400 mV"]),
            TimelinePhase(phase_name="Phase 2: 14-day continuous operation",
                          duration_weeks=2.0, dependencies=["Phase 1: Inoculation and ramp-up"],
                          deliverables=["daily acetate, headspace, biomass logs"]),
            TimelinePhase(phase_name="Phase 3: Community and integrity check",
                          duration_weeks=1.0, dependencies=["Phase 2: 14-day continuous operation"],
                          deliverables=["16S relative abundance", "membrane post-mortem"]),
            TimelinePhase(phase_name="Phase 4: Analysis and benchmark write-up",
                          duration_weeks=2.0, dependencies=["Phase 3: Community and integrity check"],
                          deliverables=["coulombic efficiency", "rate vs benchmark", "draft figure set"]),
        ],
        total_duration_weeks=9.0,
        validation=[
            ValidationMetric(metric="Volumetric acetate productivity",
                             success_threshold=">= 150 mmol/L/day for >= 7 of 14 days, n = 3 reactors",
                             measurement_method="HPLC HPX-87H linear fit on 24-h windows; one-sample t-test vs 115.2 mmol/L/day benchmark"),
            ValidationMetric(metric="Coulombic efficiency",
                             success_threshold=">= 80% to acetate over the 14-day run",
                             measurement_method="Integrated cathodic charge / 8 e- per acetate, daily"),
            ValidationMetric(metric="Cathode microbial purity",
                             success_threshold=">= 95% S. ovata relative abundance, no detected methanogens",
                             measurement_method="16S V3-V4 sequencing, QIIME2 with naive Bayes classifier"),
            ValidationMetric(metric="Rate stability",
                             success_threshold="Linear-regression slope of daily rate not significantly negative (alpha = 0.05)",
                             measurement_method="OLS with HC3 robust SE in R 4.4"),
            ValidationMetric(metric="Reproducibility across reactors",
                             success_threshold="CV of mean rate <= 25% across 3 independent reactors",
                             measurement_method="One-way ANOVA across reactors, Tukey HSD"),
        ],
        risks_and_mitigations=[
            "Methanogen contamination consumes acetate. Mitigation: add 10 mM bromoethanesulfonate as a methanogen inhibitor; monitor CH4 daily; restart on detection.",
            "Cathode biofilm fouling reduces productivity over time. Mitigation: include a controlled detachment cycle and report productivity per active biofilm area.",
            "Reference electrode drift biases applied potential. Mitigation: weekly re-calibration vs a standard Ag/AgCl; record drift in the lab notebook.",
            "Nafion crossover of acetate to anode chamber undercounts production. Mitigation: sample anode chamber daily and add to the mass balance.",
            "Power outage interrupts cathode poise. Mitigation: connect potentiostat to UPS; pre-register a 'restart and continue' protocol if interruption < 4 h.",
        ],
        applied_corrections=[],
    )


GOLDEN_PLAN_BUILDERS = {
    "crp_biosensor": crp_biosensor_plan,
    "lactobacillus_gut": lactobacillus_gut_plan,
    "trehalose_cryo": trehalose_cryo_plan,
    "sporomusa_co2": sporomusa_co2_plan,
}
